# Generated by Django 5.1 on 2025-04-04 21:39

import django.db.models.deletion
import django_extensions.db.fields
import imagekit.models.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=256)),
                ('nom', models.CharField(blank=True, max_length=256, null=True)),
                ('addresse', models.TextField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('point_fidelite', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Inconnu', max_length=50, verbose_name='Nom')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nom', unique=True, verbose_name='Slug')),
                ('numero_phone', models.BigIntegerField(blank=True, null=True, verbose_name='Numero de téléphone')),
                ('addresse', models.CharField(blank=True, max_length=50, null=True, verbose_name='Addresse')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='email', unique=True, verbose_name='Authentification ID')),
                ('photo_profil', imagekit.models.fields.ProcessedImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telephone')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('prenom', models.CharField(blank=True, max_length=30, verbose_name='Prenom')),
                ('nom', models.CharField(blank=True, max_length=30, verbose_name='Nom')),
                ('statut', models.CharField(choices=[('INA', 'Inactive'), ('A', 'Active'), ('OL', 'On leave')], default='INA', max_length=12, verbose_name='Statut')),
                ('role', models.CharField(blank=True, choices=[('OP', 'Operative'), ('EX', 'Executive'), ('AD', 'Admin')], max_length=12, null=True, verbose_name='Rôle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['slug'],
            },
        ),
    ]
