# Generated by Django 5.1 on 2025-04-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('IN', 'Invité'), ('AD', 'Admin')], max_length=12, null=True, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='statut',
            field=models.CharField(choices=[('ON', 'Active')], default='ON', max_length=12, verbose_name='Statut'),
        ),
    ]
