# Generated by Django 5.1 on 2025-04-06 14:18

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentifications', '0003_alter_profile_role_alter_profile_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_profil',
            field=imagekit.models.fields.ProcessedImageField(upload_to='profile_pics'),
        ),
    ]
