# Generated by Django 5.1 on 2025-04-06 14:49

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentifications', '0004_alter_profile_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_profil',
            field=imagekit.models.fields.ProcessedImageField(default='profile_pics/avatar.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('GES', 'Gestionnaire'), ('CS', 'Caissier'), ('AD', 'Administrateur')], default='AD', max_length=12, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='statut',
            field=models.CharField(choices=[('OFF', 'Inactif'), ('ON', 'Actif'), ('OL', 'En congé')], default='ON', max_length=12, verbose_name='Statut'),
        ),
    ]
