# Generated by Django 5.1 on 2025-04-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentifications', '0005_alter_profile_photo_profil_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('GES', 'Gestionnaire'), ('CS', 'Caissier'), ('AD', 'Administrateur')], default='GES', max_length=12, verbose_name='Rôle'),
        ),
    ]
