# Generated by Django 5.1 on 2025-04-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentifications', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('OP', 'Operative'), ('EX', 'Executive'), ('AD', 'Admin')], max_length=12, null=True, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='statut',
            field=models.CharField(choices=[('INA', 'Inactive'), ('ON', 'Active'), ('OL', 'On leave')], default='ON', max_length=12, verbose_name='Statut'),
        ),
    ]
