# Generated by Django 5.1 on 2025-04-04 21:43

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='date', unique=True)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date (e.g., 2022/11/22)')),
                ('nom_client', models.CharField(max_length=30)),
                ('numero_telephone', models.CharField(max_length=13)),
                ('prix_unitaire', models.FloatField(verbose_name='Prix (Fcfa)')),
                ('quantite', models.FloatField(default=0.0)),
                ('livraison', models.FloatField(verbose_name='Frais de livraison (Fcfa)')),
                ('total', models.FloatField(editable=False, verbose_name='total (Fcfa)')),
                ('total_global', models.FloatField(editable=False, verbose_name='Montant a payé (Fcfa)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.item')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
    ]
