# Generated by Django 5.1 on 2025-04-04 21:42

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='date', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date (e.g., 2022/11/22)')),
                ('entreprise_nom', models.CharField(help_text="Nom de l'entreprise", max_length=30)),
                ('numero_telephone', models.PositiveIntegerField(blank=True, help_text="Numero de téléphone de l'entreprise", null=True)),
                ('email', models.EmailField(blank=True, help_text="Adresse email de l'entreprise", max_length=254, null=True)),
                ('addresse', models.CharField(blank=True, help_text="Addresse de l'entreprise", max_length=255, null=True)),
                ('description', models.CharField(blank=True, help_text="Pourquoi s'approvisionner ?", max_length=255, null=True)),
                ('paiement_details', models.CharField(help_text='Details de paiement', max_length=255)),
                ('montant', models.FloatField(help_text='Montant total de la facture', verbose_name='Montant en (FCFA)')),
                ('statut', models.BooleanField(default=False, help_text='Statut de paiement de la facture', verbose_name='Payé')),
            ],
        ),
    ]
