# Generated by Django 5.1 on 2025-04-04 21:44

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentifications', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='fournisseur', unique=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('statut_livraison', models.CharField(choices=[('A', 'En attente'), ('S', 'Réussie')], default='A', max_length=1, verbose_name='Statut de livraison')),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Prix d'achat (FCFA)")),
                ('valeur_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.item')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='authentifications.vendor')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['order_date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Date de vente')),
                ('sous_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_global', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('montant_taxe', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('pourcentage_taxe', models.FloatField(blank=True, default=0.0, null=True)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('montant_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.CASCADE, to='authentifications.customer')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField()),
                ('detail_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(db_column='article', on_delete=django.db.models.deletion.DO_NOTHING, to='stock.item')),
                ('vente', models.ForeignKey(db_column='vente', on_delete=django.db.models.deletion.CASCADE, related_name='saledetail_set', to='transactions.sale')),
            ],
            options={
                'verbose_name': 'Detail de vente',
                'verbose_name_plural': 'Details de vente',
                'db_table': 'sale_details',
            },
        ),
    ]
